version: '3.8'

services:
  kafka:
    image: apache/kafka:3.9.1
    container_name: kafka
    ports:
      - "9092:9092"
      - "9093:9093"
    volumes:
      - ./kafka-config/kraft/server.properties:/opt/kafka/config/kraft/server.properties:ro
    environment:
      KAFKA_CLUSTER_ID: kraft-cluster-id
    command:
      - bash
      - -c
      - |
        /opt/kafka/bin/kafka-storage.sh format \
          -t kraft-cluster-id \
          -c /opt/kafka/config/kraft/server.properties \
          --ignore-formatted
        exec /opt/kafka/bin/kafka-server-start.sh \
          /opt/kafka/config/kraft/server.properties

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    ports:
      - "8080:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: kraft-cluster
      KAFKA_CLUSTERS_0_BOOTSTRAP_SERVERS: kafka:9092
    depends_on:
      - kafka
